#!/usr/bin/env bash
# This script will configure web-02 to be identical to web-01                                  s

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "25i add_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
